laser_filter:
  ros__parameters:
    filter1:
      name: rear_blind_spot
      type: laser_filters/LaserScanAngularBoundsFilter
      params:
        lower_angle: -2.9671
        upper_angle: 2.9671
